# Generated by Django 4.1.1 on 2022-10-07 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.customer",
            ),
        ),
    ]
